CREATE TABLE  stock( id INTEGER PRIMARY KEY AUTOINCREMENT, symbol TEXT NOT NULL UNIQUE, name TEXT, watch INTEGER NOT NULL, fetch INTEGER NOT NULL);

CREATE TABLE  data(id INTEGER,  sopen INTEGER, last INTEGER, high INTEGER, low INTEGER, volume INTEGER,  avgvol INTEGER, mktcap INTEGER, stdate TEXT, cdate TEXT, ctime TEXT, FOREIGN KEY(id) REFERENCES stock(id));

